---
# - name: Copy backend files
#   become: true
#   copy:
#     src: backend.tar.gz
#     dest: /home/ubuntu/backend.tar.gz

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy backend dist files web server
  copy:
    src: backend.tar.gz
    dest: /home/ubuntu/backend/backend.tar.gz

- name: Uncompress Backend
  shell: |
    cd /home/ubuntu/backend
    tar xvzf backend.tar.gz -C .
    ls -la
- name: "Testing env variable"
  debug:
    msg: "My env variable is: '{{ lookup('env', 'TYPEORM_ENTITIES') }}'"

- name: Build
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build
    
- name: Start PM2
  shell: |
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
# - name: Start PM2
#   shell: |
#     cd /home/ubuntu/
#     tar xzvf backend.tar.gz
#     mv home/circleci/project/backend .
#     cd backend
#     sudo npm install -g npm@latest
#     sudo npm install -g webpack-dev-server
#     sudo npm install
#     sudo npm run build
#     sudo pm2 start npm --name backend -- start
